### ISSUE TITLE
Linking gdal Library/Frameworks

### ISSUE THREAD

**Issue by aladinoster** [licit-lab/symupy#59]
## Description

In OSX when trying to create the environment  `numpy` can not be loaded, this can be solved by adding `openblas` to the environment. But then `libSymuVia.dylib` cannot be loaded.

## Reproduce

In order to reproduce 

1. Git clone, checkout `dev` 
2. `conda env create -f conda/env.yaml` # fix env by adding `openblas` first
3. `python -c "import numpy"` should be ok
4. See error `OSError: dlopen(/Users/andresladino/opt/anaconda3/envs/symupy/lib/libSymuVia.dylib, 6): Library not loaded: /Library/Frameworks/GDAL.framework/Versions/2.1/GDAL`

## Expected behavior

Loading library 

## Context

- Operating System and version: OSX

## Current behavior

```
>>> cdll.LoadLibrary(DEFAULT_LIB_OSX)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/andresladino/opt/anaconda3/envs/symupy/lib/python3.9/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
  File "/Users/andresladino/opt/anaconda3/envs/symupy/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/andresladino/opt/anaconda3/envs/symupy/lib/libSymuVia.dylib, 6): Library not loaded: /Library/Frameworks/GDAL.framework/Versions/2.1/GDAL
  Referenced from: /Users/andresladino/opt/anaconda3/envs/symupy/lib/libSymuVia.dylib
  Reason: image not found
```

**Comment by aladinoster** [comment]
@floriangc  Ok for numpy! Thanks! Still getting the GDAL error though

**Comment by aladinoster** [comment]
```
❯ otool -L /Users/andresladino/opt/anaconda3/envs/symupy/lib/libSymuVia.dylib
/Users/andresladino/opt/anaconda3/envs/symupy/lib/libSymuVia.dylib:
	@rpath/libSymuVia.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Library/Frameworks/GDAL.framework/Versions/2.1/GDAL (compatibility version 22.0.0, current version 22.3.0)
	@rpath/libSymuCore.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libboost_date_time.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libboost_locale.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libboost_log.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libboost_thread.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libboost_wserialization.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libboost_filesystem.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libboost_system.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libboost_program_options.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libboost_python39.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libxqilla.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	@rpath/libxerces-c-3.2.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libodbc.2.dylib (compatibility version 3.0.0, current version 3.0.0)
	@rpath/libpython3.9.dylib (compatibility version 3.9.0, current version 3.9.0)
	@rpath/libboost_chrono.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libboost_atomic.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libboost_regex.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libboost_serialization.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 904.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.0.0)
```

**Comment by floriangc** [comment]
Ok, cmake didn't take the package from conda .. I will check that.

Adding the tests at the conda build stage could be nice for this kind of problem.

**Comment by aladinoster** [comment]
Just did something [here](https://github.com/licit-lab/symudev/pull/21) but not sure if other changes in dev are ready to go to master, I could also just take the ci commits and put them in a new branch to merge to master.

**Comment by aladinoster** [comment]
> Adding the tests at the conda build stage could be nice for this kind of problem.

Added in #60

**Comment by floriangc** [comment]
Ok I think that the last commit in `dev` fix this: https://github.com/licit-lab/symudev/commit/36ddee51bcb01c22346e71e3fc6198acd2979016
Result of otool on the libSymuvia of the conda package:
```
otool -L lib/libSymuVia.dylib
lib/libSymuVia.dylib:
	@rpath/libSymuVia.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libgdal.28.dylib (compatibility version 29.0.0, current version 29.1.0)
	@rpath/libSymuCore.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libboost_log.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libboost_thread.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libboost_wserialization.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libboost_python39.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libxqilla.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	@rpath/libxerces-c-3.2.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libodbc.2.dylib (compatibility version 3.0.0, current version 3.0.0)
	@rpath/libpython3.9.dylib (compatibility version 3.9.0, current version 3.9.0)
	@rpath/libboost_serialization.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libc++.1.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
```
I pushed the package on anaconda.
